### ISSUE TITLE
Error: 'invalid attribute key' prevents some elements from rendering"

### ISSUE THREAD

**Issue by collinsmarra** [patternfly-yew/patternfly-yew#66] opened 2023-06-29 14:40 UTC
I have been migrating to v0.5 and I am getting this even on pages where I am not using `r#type`. This is what pops in the console

![image](https://github.com/patternfly-yew/patternfly-yew/assets/48761741/e7375122-7164-4972-b343-1d2adad3aefc)

**Comment by ctron** [comment] 2023-06-30 08:30
hm, that's interesting. Never seen that. Hard to tell without context. Can you share some code or maybe create a reproducer?

**Comment by phill-85** [comment] 2023-06-30 10:12
are you using head, or the v0.5.0-alpha.2 tag?

I fixed a similar issue to do with lists, think this was pre v0.5.0-alpha.2 tag though.

https://github.com/patternfly-yew/patternfly-yew/commit/e0909dd1fa8ad6a08c63a357cc2f7c9538e517bc looks like it could be the problem if you're using head... the `button` tags (html elements because the 'b' is lower case) should have `ref` instead of `r#ref`.

`Button` tags (note the capitalized B) are PatternFly Yew components, and should use `r#type`.

**Comment by ctron** [comment] 2023-06-30 11:52
@phill-85 thanks, good catch, should be fixed in fa85d131c7a41a1f1e351994248173458dfae63b

**Closed** 2023-06-30 11:52 UTC
Labels: need info
